### ISSUE TITLE
gen dataset error

### ISSUE THREAD

**Issue by duckQuu** [omarperacha/ps4-dataset#3]
/usr/local/lib/python3.10/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/root/ps4-dataset/main.py", line 75, in <module>
    generate_embedings('ps4_data/ps4_data/data.fasta')
  File "/root/ps4-dataset/ps4_data/get_embeddings.py", line 24, in generate_embedings
    all_seqs = __read_fasta(fasta_path)
  File "/root/ps4-dataset/ps4_data/get_embeddings.py", line 58, in __read_fasta
    with open(fasta_path, 'r') as fasta_f:
FileNotFoundError: [Errno 2] No such file or directory: 'ps4_data/ps4_data/data.fasta'

**Comment by omarperacha** [comment]
thanks, this should be fixed in latest patch https://github.com/omarperacha/ps4-dataset/pull/4

**Comment by duckQuu** [comment]
hello omar, do you have any tips for me to improving my machine learning
skills?, maybe a github or any other sources for me to learn 😁, im still
an undergrad 😁, thankyou
